# Generated by Django 6.0.7 on 2026-08-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
