# Generated by Django 6.0.7 on 2026-08-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
